// <auto-generated />
using BowlingLeagueManagerV2Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BowlingLeagueManagerV2Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241004224950_create-team-table")]
    partial class createteamtable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BowlingLeagueManagerV2Backend.Models.Bowler", b =>
                {
                    b.Property<long>("BowlerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BowlerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BowlerId");

                    b.ToTable("Bowlers");
                });

            modelBuilder.Entity("BowlingLeagueManagerV2Backend.Models.BowlerLeagueCombo", b =>
                {
                    b.Property<long>("BowlerLeagueComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BowlerLeagueComboId"));

                    b.Property<int>("Average")
                        .HasColumnType("int");

                    b.Property<long>("BowlerId")
                        .HasColumnType("bigint");

                    b.Property<int>("HighestGame")
                        .HasColumnType("int");

                    b.Property<int>("HighestSeries")
                        .HasColumnType("int");

                    b.Property<long>("LeagueId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalGamesBowled")
                        .HasColumnType("int");

                    b.Property<int>("TotalPins")
                        .HasColumnType("int");

                    b.HasKey("BowlerLeagueComboId");

                    b.ToTable("BowlerLeagueCombos");
                });

            modelBuilder.Entity("BowlingLeagueManagerV2Backend.Models.League", b =>
                {
                    b.Property<long>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LeagueId"));

                    b.Property<int>("HandicapBase")
                        .HasColumnType("int");

                    b.Property<string>("LeagueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxBowlersPerTeam")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfWeeks")
                        .HasColumnType("int");

                    b.HasKey("LeagueId");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("BowlingLeagueManagerV2Backend.Models.Series", b =>
                {
                    b.Property<long>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeriesId"));

                    b.Property<long>("BowlerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Game1")
                        .HasColumnType("int");

                    b.Property<int>("Game2")
                        .HasColumnType("int");

                    b.Property<int>("Game3")
                        .HasColumnType("int");

                    b.Property<long>("LeagueId")
                        .HasColumnType("bigint");

                    b.Property<int>("SeriesTotal")
                        .HasColumnType("int");

                    b.Property<long>("WeekId")
                        .HasColumnType("bigint");

                    b.HasKey("SeriesId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("BowlingLeagueManagerV2Backend.Models.Team", b =>
                {
                    b.Property<long>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeamId"));

                    b.Property<long>("LeagueId")
                        .HasColumnType("bigint");

                    b.Property<int>("PointsLost")
                        .HasColumnType("int");

                    b.Property<int>("PointsWon")
                        .HasColumnType("int");

                    b.Property<int>("TeamAverage")
                        .HasColumnType("int");

                    b.Property<int>("TeamHandicap")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
